export const COLORS = {
  bg: "#050714",
  bg2: "#080D1F",
  card: "#10182F",
  text: "#F8FAFC",
  muted: "#A8B3C7",
  dim: "#64748B",
  cyan: "#22D3EE",
  blue: "#355CFF",
  purple: "#A855F7",
  pink: "#EC4899",
  green: "#35D399",
  amber: "#F59E0B",
  red: "#EF4444",
} as const;

export const ACTION_COSTS: Record<string, number> = {
  "chatV2.send": 1,
  "image.generate": 1,
  "cover.generate": 12,
  "ads.generateVisual": 12,
  "ads.generateCopy": 1,
  "anime.generate": 12,
  "avatar.animate": 50,
  "image.multiedit": 12,
  "gallery.upscaleImage": 2,
  "gallery.analyzeImage": 1,
  "image.analyze": 1,
  "photo-editor.body": 3,
  "photo-editor.tryon": 3,
  "photo-editor.influencer": 12,
  "photo-editor.camera": 3,
  "video.generate": 15,
  "faceswap": 2,
  "bg.remove": 1,
  "avatar.talking": 8,
  "music.generate": 5,
  "threed.generate": 12,
  "apk.generate": 5,
};

export const PLANS = [
  { id: "free", name: "Free", points: 0, price: 0, highlight: false },
  {
    id: "premium",
    name: "Start",
    points: 120,
    price: 14.9,
    highlight: false,
  },
  {
    id: "quarterly",
    name: "Pro",
    points: 320,
    price: 34.9,
    highlight: true,
  },
  { id: "yearly", name: "Ultra", points: 700, price: 69.9, highlight: false },
] as const;

export const EXTRA_POINT_PACKS = [
  { id: "bonus-50", title: "Bônus 50", points: 50, price: 9.9 },
  { id: "bonus-120", title: "Bônus 120", points: 120, price: 19.9 },
  { id: "bonus-300", title: "Bônus 300", points: 300, price: 39.9 },
] as const;

export const STUDIO_TOOLS = [
  { key: "assistant", icon: "🧠", label: "Assistente", cost: "1 pt", color: "cyan" },
  { key: "enhance", icon: "✨", label: "Melhorar", cost: "3 pts", color: "blue" },
  { key: "body", icon: "🪞", label: "Editar Corpo", cost: "3 pts", color: "amber" },
  { key: "tryon", icon: "👗", label: "Provar Roupa", cost: "3 pts", color: "pink" },
  { key: "headshot", icon: "📸", label: "Headshot", cost: "3 pts", color: "purple" },
  { key: "camera", icon: "🎬", label: "Câmera", cost: "3 pts", color: "green" },
  { key: "product", icon: "📦", label: "Produto", cost: "3 pts", color: "cyan" },
  { key: "cover", icon: "🖼️", label: "Capas", cost: "12 pts", color: "purple" },
  { key: "anime", icon: "🎌", label: "Anime", cost: "12 pts", color: "pink" },
  { key: "avatar", icon: "👤", label: "Avatar Animado", cost: "50 pts", color: "green" },
  { key: "video", icon: "🎥", label: "Vídeo IA", cost: "15 pts", color: "cyan" },
  { key: "faceswap", icon: "🔄", label: "Face Swap", cost: "2 pts", color: "purple" },
  { key: "upscale", icon: "🔍", label: "Upscale", cost: "2 pts", color: "green" },
  { key: "bgremove", icon: "✂️", label: "Remover Fundo", cost: "1 pt", color: "pink" },
  { key: "avatarfalante", icon: "🗣️", label: "Avatar Falante", cost: "8 pts", color: "amber" },
  { key: "music", icon: "🎵", label: "Música IA", cost: "5 pts", color: "blue" },
  { key: "threed", icon: "🧊", label: "3D Model", cost: "12 pts", color: "green" },
  { key: "apkbuilder", icon: "📱", label: "APK Builder", cost: "5 pts", color: "amber" },
  { key: "redeem", icon: "🎁", label: "Resgatar", cost: "Grátis", color: "amber" },
] as const;
